import { faker } from "@faker-js/faker";
import React from "react";

export const data = [
  {
    id: 1,
    department: faker.commerce.department(),
    price: faker.commerce.price(),
    product: faker.commerce.product(),
    productAdjective: faker.commerce.productAdjective(),
    productDescription: faker.commerce.productDescription(),
    productName: faker.commerce.productName(),
    img: faker.image.image(),
  },
  {
    id: 2,
    department: faker.commerce.department(),
    price: faker.commerce.price(),
    product: faker.commerce.product(),
    productAdjective: faker.commerce.productAdjective(),
    productDescription: faker.commerce.productDescription(),
    productName: faker.commerce.productName(),
    img: faker.image.image(),
  },
  {
    id: 3,
    department: faker.commerce.department(),
    price: faker.commerce.price(),
    product: faker.commerce.product(),
    productAdjective: faker.commerce.productAdjective(),
    productDescription: faker.commerce.productDescription(),
    productName: faker.commerce.productName(),
    img: faker.image.image(),
  },
  {
    id: 4,
    department: faker.commerce.department(),
    price: faker.commerce.price(),
    product: faker.commerce.product(),
    productAdjective: faker.commerce.productAdjective(),
    productDescription: faker.commerce.productDescription(),
    productName: faker.commerce.productName(),
    img: faker.image.image(),
  },
  {
    id: 5,
    department: faker.commerce.department(),
    price: faker.commerce.price(),
    product: faker.commerce.product(),
    productAdjective: faker.commerce.productAdjective(),
    productDescription: faker.commerce.productDescription(),
    productName: faker.commerce.productName(),
    img: faker.image.image(),
  },
  {
    id: 6,
    department: faker.commerce.department(),
    price: faker.commerce.price(),
    product: faker.commerce.product(),
    productAdjective: faker.commerce.productAdjective(),
    productDescription: faker.commerce.productDescription(),
    productName: faker.commerce.productName(),
    img: faker.image.image(),
  },
  {
    id: 7,
    department: faker.commerce.department(),
    price: faker.commerce.price(),
    product: faker.commerce.product(),
    productAdjective: faker.commerce.productAdjective(),
    productDescription: faker.commerce.productDescription(),
    productName: faker.commerce.productName(),
    img: faker.image.image(),
  },
  {
    id: 8,
    department: faker.commerce.department(),
    price: faker.commerce.price(),
    product: faker.commerce.product(),
    productAdjective: faker.commerce.productAdjective(),
    productDescription: faker.commerce.productDescription(),
    productName: faker.commerce.productName(),
    img: faker.image.image(),
  },
  {
    id: 9,
    department: faker.commerce.department(),
    price: faker.commerce.price(),
    product: faker.commerce.product(),
    productAdjective: faker.commerce.productAdjective(),
    productDescription: faker.commerce.productDescription(),
    productName: faker.commerce.productName(),
    img: faker.image.image(),
  },
  {
    id: 10,
    department: faker.commerce.department(),
    price: faker.commerce.price(),
    product: faker.commerce.product(),
    productAdjective: faker.commerce.productAdjective(),
    productDescription: faker.commerce.productDescription(),
    productName: faker.commerce.productName(),
    img: faker.image.image(),
  },
  {
    id: 11,
    department: faker.commerce.department(),
    price: faker.commerce.price(),
    product: faker.commerce.product(),
    productAdjective: faker.commerce.productAdjective(),
    productDescription: faker.commerce.productDescription(),
    productName: faker.commerce.productName(),
    img: faker.image.image(),
  },
  {
    id: 12,
    department: faker.commerce.department(),
    price: faker.commerce.price(),
    product: faker.commerce.product(),
    productAdjective: faker.commerce.productAdjective(),
    productDescription: faker.commerce.productDescription(),
    productName: faker.commerce.productName(),
    img: faker.image.image(),
  },
  {
    id: 13,
    department: faker.commerce.department(),
    price: faker.commerce.price(),
    product: faker.commerce.product(),
    productAdjective: faker.commerce.productAdjective(),
    productDescription: faker.commerce.productDescription(),
    productName: faker.commerce.productName(),
    img: faker.image.image(),
  },
  {
    id: 14,
    department: faker.commerce.department(),
    price: faker.commerce.price(),
    product: faker.commerce.product(),
    productAdjective: faker.commerce.productAdjective(),
    productDescription: faker.commerce.productDescription(),
    productName: faker.commerce.productName(),
    img: faker.image.image(),
  },
  {
    id: 15,
    department: faker.commerce.department(),
    price: faker.commerce.price(),
    product: faker.commerce.product(),
    productAdjective: faker.commerce.productAdjective(),
    productDescription: faker.commerce.productDescription(),
    productName: faker.commerce.productName(),
    img: faker.image.image(),
  },
];
